# Generated by Django 3.0.8 on 2020-07-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='ur',
            new_name='lnk',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='title',
            new_name='title1',
        ),
    ]
