# Generated by Django 3.0.8 on 2020-07-11 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='usrr',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
