# Generated by Django 3.0.8 on 2020-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_usrr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrs', models.CharField(max_length=64)),
                ('cmnt', models.CharField(max_length=64)),
                ('titl', models.CharField(max_length=64)),
            ],
        ),
    ]
