# Generated by Django 3.0.8 on 2020-07-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='title1',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
