# Generated by Django 3.0.8 on 2020-07-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200712_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userwin', models.CharField(max_length=64)),
                ('tll', models.CharField(max_length=64)),
            ],
        ),
    ]
