# Generated by Django 3.0.8 on 2020-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200712_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners1',
            name='bidd',
        ),
        migrations.AddField(
            model_name='winners1',
            name='bidd1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
