# Generated by Django 3.0.8 on 2020-07-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200712_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winners1',
        ),
    ]
