# Generated by Django 3.0.8 on 2020-07-13 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200712_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='crt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
