# Generated by Django 3.0.8 on 2020-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listings_crt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmnt',
            field=models.CharField(max_length=640),
        ),
        migrations.AlterField(
            model_name='listings',
            name='desc',
            field=models.CharField(max_length=6400),
        ),
        migrations.AlterField(
            model_name='listings',
            name='lnk',
            field=models.CharField(blank=True, max_length=640000, null=True),
        ),
        migrations.AlterField(
            model_name='winners1',
            name='desc1',
            field=models.CharField(max_length=6400),
        ),
        migrations.AlterField(
            model_name='winners1',
            name='lnk1',
            field=models.CharField(max_length=64000),
        ),
    ]
